### ISSUE TITLE
Warning for non-passive event listener

### ISSUE THREAD

**Issue by philmobley** [svgdotjs/svg.draggable.js#110]
Chrome is adding the following warning:

```
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
```

This is after calling the code like this:

```js
node.on('beforedrag', function(e) {
  // record position and track "is moving", etc
})
```

Recommend allowing to control whether the touch and drag events are passive (non-blocking) or active (cancelable)... such as:

```js
node.on('beforedrag', function(e) {
  // record position and track "is moving", etc
}, null, { passive: false })
```

**Comment by Fuzzyma** [comment]
A drag event handler cannot be passive. It wouldnt do anything in that case.
However, we could add `{passive: false}` in our code to make the warning go away.
The problem here is that google broke the web when they introduced this flag. Other browsers will instead handle that flag as if event capturing was enabled and thats not what we want

**Comment by philmobley** [comment]
According to:

https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

> This feature shipped in Chrome 51, Firefox 49 and landed in WebKit. 

Further reading shows that there is a polyfill example code that avoids capturing for browsers that do not support the passive option.

**Comment by Fuzzyma** [comment]
@philmobley in that case go ahead and create a PR to fix this. Sorry for the late reply. I was super busy with my diploma!

**Comment by Fuzzyma** [comment]
Should be fixed in current master
