### ISSUE TITLE
Adding transform: scale to parent element causes bug in safari

### ISSUE THREAD

**Issue by GuskiS** [svgdotjs/svg.draggable.js#114]
In safari, if parent element has scale, element gets dragged incorrectly. Works fine in firefox/chrome.
I'm not sure if this is an issue with svg.draggable.js or with safari itself.

Here is an example: https://jsfiddle.net/hceL518o/4/
Safari: `Version 13.0.3 (15608.3.10.1.4)`
MacOS: `OS Version 10.15.1 (19B88)`

**Comment by GuskiS** [comment]
After doing some digging, it appears to be safari issue.
`svg.getScreenCTM()` returns `a` and `b` as `1`.

For now, I'm doing this: https://jsfiddle.net/swmb3kox/3/
Basicly overwriting `point` method on `Element` where I calculate correct scale.

This probably should be in core library in `Element.screenCTM` function :thinking:

**Comment by Fuzzyma** [comment]
hmm, I am pretty sure there will be many edge cases where your method will not work. It is quite hard to replicate the correct behavior of screenCTM because it is calculated recursively from all matrices. That is also the reason why we dont try to fix these kind of browser bugs in the library. It becomes too hard of a mess. Especially when css gets involved

**Comment by GuskiS** [comment]
But you are fixing firefox bug here - https://github.com/svgdotjs/svg.js/blob/master/src/types/Matrix.js#L489
Can you think of any of the edge cases right away? I would like to test them, because for me this solution is working just fine 🤔

**Comment by Fuzzyma** [comment]
Haha yes I knew you would find that one :D. It is actually the only time we do that in the whole library because it is known to be a solid and rather small fix. However, calculating matrices on our own is a different thing.
No, I can not think of any edge cases yet. However I dislike how expensive it is with the call to rbox() AND screentCTM. I would rather report this to the vendor and lets them fix this themselves. I tried this with FF, too but they refused because they argue that it is correct that way (and I kinda can follow their argument). In case of Safari it is really a bug

**Comment by GuskiS** [comment]
I will create safari bug report for this, just need to formulate the problem correctly and create vanilla example.

Meanwhile, maybe you have better idea how to fix this rather than doing mentioned method or without rbox?

Reason why I'm adding transform to parent(or root level svg) is that it gives better performance on pan/scroll than doing it on `g` element.

**Comment by Fuzzyma** [comment]
No I dont think i know a better way. I only find it strange that rbox returns correct results while screentCTM fails. Would have thought these are related (they are in my implementation in svdom)

**Comment by GuskiS** [comment]
I've created fiddle with minimal reproduction: https://jsfiddle.net/cos4guy3/1
However, I'm not sure where to post it, cause this page https://webkit.org/reporting-bugs/ shows this message:
![image](https://user-images.githubusercontent.com/3505777/72930607-f5ea0500-3d64-11ea-803c-4371328a7849.png)

So I'm confused is it webkit or safari bug 🤔

**Comment by Fuzzyma** [comment]
I guess Apple rolls its own version based on webkit... but i am not sure either. I would follow what was said and report to apple unless this problem exists in webkit itself. You can verify this by following the first step:


>1. Check Your WebKit Version
>
>To make sure you’re not wasting your (and our) time, you should be using the latest version of WebKit before you file your bug. First, you should download the latest WebKit build archive build to be sure you have the latest version. If you’ve done this and you still experience the bug, go ahead to the next step.
