### ISSUE TITLE
Image ClipPath not moving relative to dragged group

### ISSUE THREAD

**Issue by mklauss** [svgdotjs/svg.draggable.js#115]
I'm updating from SVG.js 2.7 to 3.0 and have hit a snag. I have a series of svg groups (puzzle pieces to be exact), each contain an image that is clipped with a unique path. In 2.7 when I apply .draggable to the group the clipPath applied to the image moves relative to the dragged group. In 3.0 the clipPath remains stationary.

I tried moving the clipPath out of the `<defs>` block and nest it into the group, but that only produces and error when try to drag the group. 

How do I move the clipPath along with the dragged group? 
 
Here's an example of the SVG markup....

```svg
<g id="workspace">
	<g id="piece_k7q6yysx_0" class="draggable" data-col="0" data-row="0" data-x="660" data-y="426" data-dim="100" data-cx="710" data-cy="476">
		<g>
			<path d="M608 385C608 ... 385Z " fill-opacity="0.1" fill="#dedede" stroke-width="1" stroke="#ffffff"></path>
			<g clip-path="url(#SvgjsClipPath1000)">
				<image width="600" xlink:href="https://asset---north-carolina.bldg15.net/img/2/8/2816b2e8-cd49-4382-8701-4ce464fdd19f/Grandfather%20Mountain%20Sunrise%20with%20Hiker-crop(1.000,0.848,0,0.083,r6).1bf0e7c1.jpg" x="608" y="385"></image>
			</g>
			<circle r="0.5" cx="658.5" cy="435.5" opacity="0.25"></circle>
		</g>
	</g>
</g>
<defs>
	<clipPath id="SvgjsClipPath1000">
		<path d="M  660,426 C  660,426  ....  660,426  660,426 z "></path>
	</clipPath>
</defs>
`

**Comment by Fuzzyma** [comment]
The way a group is moved was changed in version 3 to make it consistent with all other movements.
As you might have realized, `move()` always moves an element by its upper left corner (even circles for example). However, that this is not the whole truth. What actually happens is, that elements are moved by their upper left corner of their bounding box. This never worked for groups in 2.x so it was rewritten.
While in 2.x the group was simply translated with a transformation, 3.x instead moves all elements inside the group so that the new bounding box matches the moved box. This ofc also influences the clippath of the element which is actually moved now.

I cannot think of a solution on top of my head. Thats why I ask you to create a jsfiddle or codepen to show the issue and to give me something to fiddle around with

**Comment by mklauss** [comment]
I'll certainly work up and example for you.

**Comment by mklauss** [comment]
Here's a jsFiddle 
[https://jsfiddle.net/mklauss/du824bLe/3/](url)

**Comment by Fuzzyma** [comment]
Can you give me a fiddle with the old version too?

**Comment by mklauss** [comment]
Here's an example that is working. It uses the 2.7 lib.
https://jsfiddle.net/mklauss/hwoL8bdr/1/

**Comment by Fuzzyma** [comment]
Jeah ok as I suspected, its because if the new way group movement is handled.
I updated your version so that it mimics the old behavior: https://jsfiddle.net/Fuzzy/pkac5z37/12/

**Comment by mklauss** [comment]
Thanks for the example, that is working for me, I appreciate your help with this.
