### ISSUE TITLE
use svg.draggable.js  click element 

### ISSUE THREAD

**Issue by miss-tree** [svgdotjs/svg.draggable.js#122]
ele.on("dragmove.namespace",(e)=>{  })   
or
ele.on("dragend.namespace",(e)=>{  })   

click element ,click no response

**Comment by miss-tree** [comment]
but element  move

**Comment by Fuzzyma** [comment]
sorry, what?

**Comment by miss-tree** [comment]
Maybe I didn't describe it clearly enough,

I'm calling       element .draggable()
I want to get coordinates during dragging

this.draw = SVG()
      .addTo(this.id)
      .size(2000, 600)
var group = this.draw.group()
var image=group.image(randomImg)
group.draggable()
group.on('dragmove', function(e) {
        e.preventDefault()
        const { handler, box } = e.detail
        let { x, y } = box
        handler.move(x, y)
 })

But after I call, I click the element on the page, and the element moves, which I don't want. Using the click event has no effect

image.on('click',()=>{
        console.log('hello')
      })

**Comment by Fuzzyma** [comment]
A drag consists of a mousedown, a drag and a mouseup. A click consists of mousedowm and mosueup.
The plugin prevents the mousedown so the click never happens. You can bind to beforedrag and dragend, set a flag in beforedrag and check in dragend if the shape actually moved. If not, execute click-code

**Comment by miss-tree** [comment]
Thank you very much. It was a success. Whether to execute the click event code by comparing the coordinates before and after clicking

**Comment by pierralex** [comment]
@Fuzzyma Do you want to keep the fact that click is not "natively" supported for draggable elements? It seems strange to me that we need additional code to "get back" click working. If you agree, I can try to make a PR to fix this. The idea would be to keep preventing mousedown but to trigger click on mouseup if the drag did not occur. What do you think?

**Comment by Fuzzyma** [comment]
It is not advises to trigger native events yourself. That's why I am not a fan of that idea. However, we can add a custom event which the user can bind to to solve this problem.

BTW after reading my posts of this thread I am unsure why the click event does not fire. I read up on that issue and click is actually a completely separate event and should fire anyway.
However since it seems not to we can add the custom event as a rescue hook

**Comment by pierralex** [comment]
Sorry, I double-checked but I have the opposite behaviour.
Just clicking works fine. But if I drag, I ave both a dragend and a click event. Which is unexpected from my point of view. So my new question is: should click be deactivated if a drag event occured?
This is not really blocking for me but I can give a look if you want.

**Comment by Fuzzyma** [comment]
For that to work you would need to bind to the click event for the sole purpose of canceling it when a move happend. I dont think thats useful especially because people might want to use the click event no matter if a drag happend or not

**Comment by pierralex** [comment]
Here is a very common usage:
Take a rectangle with a text inside. I am used to (as biased by most
existing applications) dragging for moving the box and clicking to edit the
text.
In the current behaviour, dragging would move and edit the box. It is
counter-intuitive for me. I would prevent click event if drag occurred by
default (or at least make it configurable in order to prevent a lot of
people from writing the same code again and again).
This is just my opinion and I can totally manage with the current behavior
but I think it can be improved a bit (and I am ready to help for
implementation :))

**Comment by Fuzzyma** [comment]
Alright, if you are that eager to help, add an option called "cancelClick" which defaults to false and only bind to click when this option is true
