### ISSUE TITLE
Unable to drag imported element 

### ISSUE THREAD

**Issue by aloisclerc** [svgdotjs/svg.draggable.js#124]
In my project I would like to import an string that is an element using the `draw.svg('<rect>')` function.
The `draggable()` function works perfectly if I create an element with the `draw.rect()` function but not when it is imported with a string. My example code is below:

```html
<div id="canvas"></div>
<script>  
     var draw = SVG().addTo('#canvas').size(300, 300)  
     let newCircle = draw.svg('<circle cx="50" cy="50" r="50"/>');
     let newCircle2 = draw.circle(200);
     newCircle.draggable();
     newCircle2.draggable();
</script>
```

newCircle2 is draggable, but newCircle is not.

Any idea why functions from .svg aren't draggable?

**Comment by Fuzzyma** [comment]
Importing using `svg()` will not give you back the imported element because it is totally possible to import more stuff at once e.g. `svg('<rect ...><circle ...>')`. What you get back instead is the parent in which the element was imported (in your case `draw`). So you might want to look for the `last()` element in your parent and maket it draggable:

```js
     var draw = SVG().addTo('#canvas').size(300, 300)  
     draw.svg('<circle cx="50" cy="50" r="50"/>');
     draw.last().draggable()
```
