### ISSUE TITLE
draggable for svg.js 2.7 ?

### ISSUE THREAD

**Issue by froid24** [svgdotjs/svg.draggable.js#125]
I see on the bottom that this requires svg.js 3.0... however on the svg.js website it is listed as available also for svg.js 2.7... is there a version that works on 2.7?

It is so frustrating, because I have to build a tool to draw/drag/resize svg elements. On svg.js 3.0 resize does not work, on 2.7 it isems that the draggable doesn't work. I just cannot see one without the other...

Any hints appreciated. Thanks!

**Comment by Fuzzyma** [comment]
Yes there is. While all plugins which work with v3 are published under the `@svgdotjs/...pluginname` namespace, you can find the version for v2 without the namespace (in this case just `svg.draggable.js`).

In case of the draggable plugin it is even a bit more complicated because I published one version by accident. So what you want is to do `npm i svg.draggable.js@2`

In the long run however, you might want to switch to svg.js v3 - even if the plugins are not ready yet
