### ISSUE TITLE
problem with rotate

### ISSUE THREAD

**Issue by ThorsenRune** [svgdotjs/svg.draggable.js#52]
Dragging a rotated group behaves oddly (moves at rotation angle with mouse) in chrome v 46.
Example
r=draw.rect(100,50)
g=draw.group().add(r)
g.rotate(20).draggable()

Is it intended?

**Comment by Fuzzyma** [comment]
No of course not. I looked into this and could not find a reason for this behavior.
It has something to do with all this transformation stuff.
However you could easily avoid this problem by wrapping the rotatet group into another group which you can drag normally

**Comment by spikyian** [comment]
I am also experiencing this problem. The event.detail.px,event.detail.p.y coordinates passed are relative to coordinate system which is rotated by the angle of the element.

I think this is caused by DragHandler.prototype.transformPoint with the return statement performing a transform of this.m: return this.p.matrixTransform(this.m). I assume that m includes the element's rotation but I think it should only perform scaling and translation to get the correct coordinates.

**Comment by Fuzzyma** [comment]
Its because we are trying to make absolute transformations which is totally nonsense and leads by definition to mathematical errors. The solustion is to apply the drag as relative transformation to the group

**Comment by Fuzzyma** [comment]
Test the latest commit

**Comment by burnpanck** [comment]
This fix fails to respect the movement constraints for groups, see my inline comment in #52.

**Comment by Fuzzyma** [comment]
Constraints are applied to the elements system and not to the screens system. Therefore the behavior is correct.

**Comment by burnpanck** [comment]
No, the issue I was pointing at has nothing to do with coordinate systems. With that, it is also unrelated with the issue here (except for the fact that it was introduced with the fix here). Therefore, I opened a new issue: #67.
