### ISSUE TITLE
Drag parent object from manipulator?

### ISSUE THREAD

**Issue by mooreaa** [svgdotjs/svg.draggable.js#64]
Is there a way to have a region active the drag event for a group? Imagine a finder window, you want to drag the header bar on a window w/o making the whole thing dragable.

**Comment by Fuzzyma** [comment]
So what you want is a handle? Sure - catch the dragmove event of the handle and draw the parent object instead. Or just relay the mouse events to the parent object

**Comment by Andreslav** [comment]
@Fuzzyma, I'm trying to do something like this: moving a group, instead of a square. And everything would be fine, but with increasing dragging breaks ...

What is the disadvantage of my function?

```
function draggable(group) {
	let a = [];
	rect.on('dragstart', function(e){
		e.preventDefault()
		a.x = e.detail.p.x - group.transform().x;
		a.y = e.detail.p.y - group.transform().y;
	})
	rect.draggable().on('dragmove', function(e){
		e.preventDefault();
		group.move(~~e.detail.p.x - ~~a.x, ~~e.detail.p.y - ~~a.y);
	})
}
```

Probably except you to me no one will help)

**Comment by Fuzzyma** [comment]
Not all questions are answered in one day. Especially not if I find no time to do so!
And again: this is a question for stackoverflow. There are FAR more people to help you than in an abandoned issue on github

I dont get why you just call `draggable()` on the group.
This is completely fine: https://jsfiddle.net/Fuzzy/L6b0m8x5/3/

If you dont want the other stuff in the group act as handler you can just catch the mouseevents there and stop propagation:

```js
let handler = group.rect(10, 10)
group.each(function () {
  if(this == handler) return
  this.on('mousedown', function (ev) { ev.stopPropagation() })
})
```

**Comment by Andreslav** [comment]
> Not all questions are answered in one day. Especially not if I find no time to do so!
And again: this is a question for stackoverflow. There are FAR more people to help you than in an abandoned issue on github

I understand. I asked the stackoverflow [question](https://stackoverflow.com/questions/50881345/moving-at-high-magnification), but there was no solution. Maybe it was necessary to simplify the code as much as possible ...

> If you dont want the other stuff in the group act as handler you can just catch the mouseevents there and stop propagation:

Thanks for the idea, 
I'll try. And yet, I do not understand why my math does not work?

**Comment by Fuzzyma** [comment]
> I understand. I asked the stackoverflow question, but there was no solution. Maybe it was necessary to simplify the code as much as possible ...

As you can see, someone (me) discussed with you in the comments. But I hadnt any time to create an answer. Beside that you were dealing with a typical xy problem where you ask y but really need a solution for x.
Imo there is no point in wondering about the maths here. When you look into the draggable code you can see, that mouse coordinates get transformed to match the coordinate system of the dragged element. These transformations can lead to problem as soon as the transformation changes (which is the case when you start scaling). Beside that, the parameters you get from `transform()` are not always correct (fixed in 3.0). I am not sure if this maybe leads to problems here, too.

However, the simplest solution is mostly the best. In that case it means: Let the plugin do the maths

**Comment by Andreslav** [comment]
It seems it happened!
You're right. I apologize for the excessive perseverance.

**Comment by Fuzzyma** [comment]
I am glad that its working now! You might want to answer or delete your own question on stackoverflow so we dont have an unanswered question around :)
