### ISSUE TITLE
Drag constraints of type `object` are not applied when dragging SVG groups.

### ISSUE THREAD

**Issue by burnpanck** [svgdotjs/svg.draggable.js#67]
Furthermore, with `function` constraints, there is most likely a problem too.

At the beginning of the handler `DragHandler.prototype.drag`, it essentially starts by deriving two coordinates related to the current drag position: `(x,y)` as absolute coordinates, and `(gx,gy)` relative to the drag-start.
Then, if the constraint is of `object` type, the absolute limits are then applied to `(x,y)`. Finally, if the element is not a group, it is repositioned using `.move(x,y)`, if it is a group, it's matrix is instead translated by `(gx,gy)` with respect to the matrix at dragstart. Clearly, that does not restrict the constraints applied to `(x,y)` only. 

With constraints of type `function`, the coordinates are applied to the element via the `x` and `y` accessors, independent if it is a group or not. I'm not sure, but I have the feeling that this shouldn't work at all for groups and the like.

**Comment by raven78** [comment]
quick fix:
starting at line 160 insert 
```
gx = x - this.startPoints.box.x
```
and
```
gy = y - this.startPoints.box.y
```
after each assigment of new values to x and y.

**Comment by Fuzzyma** [comment]
@burnpanck @raven78 in which way do you use constraint? Can I see your usecase? I think about changing the way constraints are applied to simplify things a bit

**Comment by Fuzzyma** [comment]
I pushed the fix you provided. This fixes it for constraints of type object but wont work correctly with functions

**Comment by raven78** [comment]
I'am using only object constraints. I will test with function and come back with a comment on the matter.

**Comment by raven78** [comment]
My use case is pretty simple.
I have some UI elements  composed in groups. All groups are in one container and they can be dragged inside the bound of parent container (svg).  

I did some tests with functions too and i have some conclusions:
It works with functions too, given you drag relatively slowly on the screen. If you drag too fast, then bounds don't work as expected. The element dragged is not updated as fast as the event fires and it receives a stop from the bounds too early. If you retry you can get it at the bounds. This problem is not apparent on object constrains.

The problem when dragging transformed groups or nested svg (skew, rotate) comes from the fact that you take in to account transformations applied to the dragged element when you should drag relative to transformations applied to parent element.

Example:
Lets take as an example a sliding puzzle
 ![Sliding puzzle - wikipedia](https://upload.wikimedia.org/wikipedia/commons/a/a5/Batgirl.gif)
You have a puzzle board that contains all the puzzle pieces.
In order to play you need to drag each puzzle piece. 
If you want to simulate a perspective you skew the puzzle board.
Now each piece must be dragged in the new coordinate system of the board.
The board itself as a group must move in the coordinate system of its parent.

Hope this helps.

**Comment by raven78** [comment]
Another example:
Water pipe game
![Google Play - Water Pipe Game](https://lh3.googleusercontent.com/CX1t2HeED5VpAI2MM_KXArk3c6QKSU1_sRlQFGxruD7CrVJhNXI1R97jbqkpOjXgQwA=h200)
Same as above except that now each piece can be rotated and still dragged on the board coordinate.

Currently there is no difference between 
```javascript
parentSVG.nested().rotate(20).rect(50, 50).draggable({
	minX: 0,
	minY: 0,
	maxX: 150,
	maxY: 150
})
```
and

```javascript
parentSVG.nested().rect(50, 50).rotate(20).draggable({
	minX: 0,
	minY: 0,
	maxX: 150,
	maxY: 150
})
```

**Comment by Fuzzyma** [comment]
Important thing to note here is that transformations are not allowed on `<svg>` elements. It might work in some browsers but it's not in the specs. So for transformations you use group instead. 
The problem with groups is, that they can only be moved with transformations, too.
That leads to problems when using constraints because you just don't know where the group is currently (transformations influence each other. E. G. Rotation leads to Transformation, too). You Ofc can pull the e and f values from the matrix but you don't know if this is the scaled translation or the normal translation. 
So of you don't know where the group is, you can't check for the position values and therefore can't constrain it. 
Even if you would know that you need to constrain you would be in the need to set an absolute position on the group and that's also not possible without destroying all earlier transformations

**Comment by raven78** [comment]
> Important thing to note here is that transformations are not allowed on `<svg>` elements.

Then maybe `someSVG.nested().rotate(20)` should raise an error...

> You Ofc can pull the e and f values from the matrix but you don't know if this is the scaled translation or the normal translation.
So of you don't know where the group is, you can't check for the position values and therefore can't constrain it.

That’s not totally true, what you louse is the coordinates of anchor point around which you made your transformations.
Not the position of the group (e and f)… A,b,c & d tells you everything about group space. 

Anyway, using function constraints I can do whatever type of constraints I nedd.

To fix the problem with groups constraints when you constrain with a function then you should make the same check if it is a group or not and calculate gx and gy, as you do when it’s an object:

```javascript
// line 128 - 154
// move the element to its new position, if possible by constraint
var tx, ty // NEW
if (typeof c === 'function') {
  var coord = c.call(this.el, x, y, this.m)
  tx = this.el.x() // NEW
  ty = this.el.y() // NEW

  // bool, just show us if movement is allowed or not
  if (typeof coord === 'boolean') {
    coord = {
      x: coord,
      y: coord
    }
  }

  // if true, we just move. If !false its a number and we move it there
  if (coord.x === true) {
    tx = x // NEW
    // old line
  } else if (coord.x !== false) {
    tx = coord.x // NEW
    // old line
  }

  if (coord.y === true) {
    ty = y // MODIFYED
    // old line
  } else if (coord.y !== false) {
    ty = coord.y // MODIFYED
    // old line
  }
  // NEW FROM HERE
  if (this.el instanceof SVG.G) {
    gx = tx - this.startPoints.box.x
    gy = ty - this.startPoints.box.y
    this.el.matrix(this.startPoints.transform).transform({x: gx, y: gy}, true)
  } else {
    this.el.move(tx, ty)
  }
  // TO HERE
} else if (typeof c === 'object') {
```
You could refactor to 
``` javascript
// Line 128 - 177
// move the element to its new position, if possible by constraint
var tx, ty
if (typeof c === 'function') {
  var coord = c.call(this.el, x, y, this.m)
  tx = this.el.x()
  ty = this.el.y()

  // bool, just show us if movement is allowed or not
  if (typeof coord === 'boolean') {
    coord = {
      x: coord,
      y: coord
    }
  }

  // if true, we just move. If !false its a number and we move it there
  if (coord.x === true) {
    tx = x
  } else if (coord.x !== false) {
    tx = coord.x
  }

  if (coord.y === true) {
    ty = y
  } else if (coord.y !== false) {
    ty = coord.y
  }
} else if (typeof c === 'object') {
  // keep element within constrained box
  tx = x
  ty = y
  if (c.minX != null && x < c.minX) {
    tx = c.minX
  } else if (c.maxX != null && x > c.maxX - box.width) {
    tx = c.maxX - box.width
  } if (c.minY != null && y < c.minY) {
    ty = c.minY
  } else if (c.maxY != null && y > c.maxY - box.height) {
    ty = c.maxY - box.height
  }
}
if (this.el instanceof SVG.G) {
  gx = tx - this.startPoints.box.x
  gy = ty - this.startPoints.box.y
  this.el.matrix(this.startPoints.transform).transform({x: gx, y: gy}, true)
} else {
  this.el.move(tx, ty)
}

// so we can use it in the end-method, too
```

**Comment by raven78** [comment]
**Caveat nr. 1**
If you return either true/false or `{x: true/false, y: true/false} from your function and you drag to fast, then your element will remain in last position where it received a true value (there is no way to determine your bounds).

**Caveat nr. 2**
When you use object bounds, the bounds are applied tacking into consideration the bbox of your element so that the element is always visible.
 When you use a function you must subtract the element bbox width/height from your max x/y to accomplish the same result.

Ex:
```javascript
function (x, y, m) {
  return {
    x: x >= minX && x <= maxX – this.bbox().w, // replace minX & maxX with your values
    y: y >= minY && y <= maxY – this.bbox().h // replace minY & maxY with your values
  }
}
```

**Comment by burnpanck** [comment]
Didn't follow all the comments, I just want to state my use-case: I have none. I needed to know the origin of the transformed coordinate system of the dragged group element during and after the drag, which was not directly available on information delivered to the callbacks, so I dug through the code to find a way to derive that information, which is when I identified this bug.

**Comment by raven78** [comment]
Now I understand what you mean.
My code above does not help you it just makes drag handler more uniform around functions and object constraints. 

**Current behavior is:**
During the first drag, your origin is where it should be and everything seams OK.
When you drag again problems start to arise.
Each time you start dragging group origin get shifted/miscalculated  (`this.startPoints`) and as such bounds are shifted.
From this behavior I started to look at `DragHandler.prototype.start` which lead me to two contenders `this.startPoints.transform` and `DragHandler.prototype.getBBox`.

This may lead to svg.js matrix and transform.
I will look into this when a have some spare time. My 10 month daughter gets all of it.

**Comment by Fuzzyma** [comment]
You see it is not as easy as it looks. Thats why I asked for the use case. I wanted to know of the constraints are more often used in screen coordinates or in user space coordinates. The former would allow me to implement the constraints in a more consistent manner because I just have to check the mouse coordinates (and its always an untransformed rectangle)

**Comment by clusterberries** [comment]
Hi @Fuzzyma !
I'm using draggable() with config object that contains minX, minY, maxX, maxY. This works good for simple elements, but when I'm trying to drag a group, the min/max values are applied with issues. After some investigation I found out that this code from `getBBox` method causes wrong behavior:

```
if (this.el instanceof SVG.G || this.el instanceof SVG.Use || this.el instanceof SVG.Nested) {
    box.x = this.el.x()
    box.y = this.el.y()
}
```

What is the purpose of this block of code?

**Comment by clusterberries** [comment]
Hm, after some investigation I found out that bbox returns correct value for group only the first time, as @raven78 mentioned above. But it seems like I have a solution. I changed the code from previous comment to this

```
if (this.el instanceof SVG.G || this.el instanceof SVG.Use || this.el instanceof SVG.Nested) {
    box.x += this.el.x()
    box.y += this.el.y()
}
```

It works for me.

**Comment by Fuzzyma** [comment]
@clusterberries The code you mentioned deals wit group dragging. Groups dont have a position. They just group elements togeher. You can think of them as a selection in photoshop. You can drag the selection around, rotate it, scale it and so on. Thats how groups work in svg. So to drag a group we need to translate it. However, since there could be already a transformation present on the group it can lead to trouble when we just set the translation. Thats why it is applied relatively to the last position.

The code mentioned fixes the box given from bbox (its not "wrong" but not useful in our case).

However, this plugin needs an update. As soon as 3.0 is out (and with it finally stable transformation) much can be simplified and work better then.
