### ISSUE TITLE
Question - how to create drag constraints after transforms like rotation

### ISSUE THREAD

**Issue by cyberwombat** [svgdotjs/svg.draggable.js#72]
I've been working on creating some kind of drag constraint math in the `dragmove` event as the default bounds do not work with transforms but I am having a heck of a time. I have a second hidden shape with the opposite rotation and I use `shape.point()` to translate the drag coordinates to screen ones. That works - I know when out of bounds but it's what happens when trying to get the fallback coordinates (since I can move up/down Y with X being out of bounds and fixed) and that is killing me.  Always seems a little off. Do you have code samples of something like this? I am sure this came up before for someone but I am not finding much.

Thanks

**Comment by Fuzzyma** [comment]
You can take a look into the implementation of the `point()` method which will give you a clue how this transformation is achieved. If you need to transform something back, you would make the same thing but not inversed.

**Comment by cyberwombat** [comment]
Its actually what I am using. Unfortunately calculating the opposite turns out to only be a small step in doing this. There are some issues with boundary calculation during the mouse move that I have not resolved and probably giving up on. Thanks though.

**Comment by cyberwombat** [comment]
Here's my attempt. https://codepen.io/cyberwombat/pen/dzOKGd

**Comment by Fuzzyma** [comment]
I alreay tried to do things like you do atm. However I was never able to make it work properly. I guess I cant be much of a help in this case. The problem is, that you dont know exactly where to "snap" the element to. You need to constantly check all corners of the rect and if they are leaving teh boundary and have a logic which calculates the best position to stay in the boundary. Not that easy

**Comment by cyberwombat** [comment]
Did it! Check out the pen
