### ISSUE TITLE
When the SVG is nested inside the SVG, the drag effect is unusual

### ISSUE THREAD

**Issue by zhb0110** [svgdotjs/svg.draggable.js#73]
When the SVG is nested inside the SVG, the drag effect is unusual,it looks like the reason for the attribute of the child SVG "viewBox":
`<svg id="SvgjsSvg1006" width="360" height="502" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" viewBox="0 0 360 502"><defs id="SvgjsDefs1007"></defs><rect id="SvgjsRect1008" width="360" height="502" fill="#ffffff"></rect><svg id="SvgjsSvg1009" x="169.2883529663086" y="139.06615257263184" style="overflow: visible;" viewBox="0 0 750 750"><rect id="SvgjsRect1010" width="150" height="50" rx="0" ry="10" x="0" y="0" fill="#ffffcc"></rect></svg></svg>`

**Comment by Fuzzyma** [comment]
please create an example on jsfiddle

**Comment by razvanioan** [comment]
@zhb0110 

Your issue I don't think is due to this library, but how SVG's are working.

You're defining a nested SVG of width / height of 157.5 which contains elements of width / height of 750.

Of course that the `viewBox` & `preserveAspectRatio` were taking care of the correct viewport, as without them the nested SVG content doesn't fit inside the element (which is smaller)

Take a look on[ your forked fiddle](https://jsfiddle.net/razvanioan/gfttxtfs/1/) where I've removed viewBox, preserveAspectRatio (and other things like XMLNs which are not required) from your nested SVG, and grouped everything and scaled it with a ratio of 0.21 (which is 157.5 / 750)
