### ISSUE TITLE
SVG.off removes all listeners related to draggable, not only from the current element

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.draggable.js#90]
When SVG.off is being performed it's removing all listeners that we have of that type, as the code is like this: `SVG.off(window, 'mouseup.drag')`.

This is normally not a problem because you are only dragging 1 element at a time so it's not a problem if we remove all listeners (besides maybe being a bad pattern that the element should only touch its events).

I encountered this because of a 'synchronized' dragging I'm doing. When I move 1 rectangle I want to move also another rectangle, like this: https://jsfiddle.net/c4f8udrb/14/

You can test it by moving the blue rectangle. To achieve that I'm basically relaying the event from rect 1 to  rect 2:

````
rect.on('mousedown', function(e) {
  rect2.fire(new MouseEvent(e.type, e))
});

rect.on('mouseup', function(e) {
  rect2.fire(new MouseEvent(e.type, e))
});

````

Problem is, mouseup never gets called to rect2 since rect1 mouseup removes all listeners on mouseup. For me it's not a big deal, I just don't get the dragend event for that rect2 but everything seems to work OK. 

I suggest we change to using named functions as listeners so we can off just of that listener: `SVG.on(window, 'mouseup.drag', this.mouseUpHandler)`. 

Is there any possible problems doing this or any other feedback?

**Comment by Fuzzyma** [comment]
The only problem i see is, that `this` is wrong in the mouseUpHander. Because you give a function as listener which is not bound. However there is a good workaround for this which is just doing `SVG.on(window, 'mouseup.drag', this.mouseUpHandler, this)` instead. That will do the binding for you.

I am just not sure, if it will work. Because you bind the "this.mouseUpHandler"-function multiple times and its always the same function. So passing a listener could result in exactly the same behavior.

The next thing i can think of is having an id generated when the draghandler is created and you use the id as namespace. That will create unique namespaces and with them you can savely remove the correct handlers

**Comment by pjfsilva** [comment]
Just to clarify my solution is basically this:

https://jsfiddle.net/c4f8udrb/17/

> I am just not sure, if it will work. Because you bind the "this.mouseUpHandler"-function multiple times and its always the same function. So passing a listener could result in exactly the same behavior.

I believe that doing `SVG.off(window, 'mousemove.drag', this.mouseMoveHandler)` only removes the mouseMoveHandler on that specific event type (mousemove) and for that specific instance of the object. The trick is that the handler is associated with 'this' so it's specific for DragHandler which generates a new instance for each draggable object.

I'm also not sure if `this` is wrong. I understand what you mean but on pratical tests it seems this works as intended, I didn't need to use your fix.

**Comment by Fuzzyma** [comment]
The way you did it is completely fine. What I was after was the following problem (es6 to be fast):

```js
class foo {
  handler (event) {
    // 'this' is normally the instance
    // but will be 'windows' when called from the handler
    console.log(this)
  } 

  someMethod () {
    SVG.on(window, 'mousedown', this.handler) // <-- you pass a function reference without this binding
  }
}

new foo().someMethod() 

// after some mousedown: logs windows instead of the foo instance
```

But you didnt use `this` in your handler. You declared _this outside and used it in the function.

I think it should work that way because you keep redefining the handler which creates a new function and thus will not get confused with other handlers.

To prevent MY problem (which isnt in your solution), you can pass a this binding to the SVG.on and it will bind it to the correct this.
