### ISSUE TITLE
Text moves to the right when user clicks it

### ISSUE THREAD

**Issue by anton-paskanny** [svgdotjs/svg.draggable.js#93]
When text contains letter 'A' and you click it, text starts to move. I've only noticed such behavior for text with 'A' letter.

Demo: https://codepen.io/anon/pen/LBVReK?editors=1111

**Comment by anton-paskanny** [comment]
When the second text is draggable too, it doesn't move when you click it.

**Comment by Fuzzyma** [comment]
Tried it. Still works as expected.

**Comment by Fuzzyma** [comment]
This bug is not in the code. Which browser are you using?

**Comment by anton-paskanny** [comment]
Google Chrome v67

**Comment by Fuzzyma** [comment]
Same version as me.  It totally works! Do you mind trying it at a different pc?

**Comment by clusterberries** [comment]
@Fuzzyma I also can reproduce the issue (Chrome on Windows)
When text 'A' is created, I can just click on it and it is moved a bit. If the text is different, it is not reproduced.

I debugged the code and found strange behavior.

### Good case (with 'B' letter)

1. Set `startPoints` in `start()` method. For me it is `bbox = { x: 29.40625 }, point ={ x: 39.83861541748047 }`
2. Click on text. Call `drag()` method
3. Calculate new `box` and `p`: `bbox = { x: 29.40625 }, point ={ x: 39.83861541748047 }`
4. You can see that is is equal. But we go further
5. Call `move(x, y)`. This method sets `x(x)` and `y(y)` inside. So I checked what does x() return. It return correct value 29.40625, so there is no movement of the text

### Bad case (with 'A' letter)
Here I do the same things
1. Start points are  `bbox = { x: 32.046875 }, point ={ x: 48.69164276123047 }`
2. Click and call drag()
3. New points are  `bbox = { x: 32.046875 }, point ={ x: 48.69164276123047 }`
4. Points are the same, it seems to be fine...
5. Before call `.move(x, y)`, check `x()` value. It is `33.53125`. It is bigger then it should be! That's why text is moved

**Comment by clusterberries** [comment]
@Fuzzyma It seems for me, that it is a Chrome issue, because actual x value and value from bbox() are not equal. But can we add a workaround? E.g. do not call `move` if x has not been changed

**Comment by Jakubsedmik** [comment]
I think problem is somewhere here

// fix text-anchor in text-element (#37)
    if(this.el instanceof SVG.Text){
      anchorOffset = this.el.node.getComputedTextLength();
      switch(this.el.attr('text-anchor')){
        case 'middle':
          anchorOffset /= 2;
          break
        case 'start':
          anchorOffset = 0;
          break;
      }
    }

    this.startPoints = {
      // We take absolute coordinates since we are just using a delta here
      point: this.transformPoint(e, anchorOffset),
      box:   box,
      transform: this.el.transform()
    }

the library bad calculate anchorPoint
